## service 'ManipulationCommand.srv'

## REQUEST

# home position (override the target_position command)
bool home_position

# tip in that position
geometry_msgs/Point target_position

# max distance from the target
float32 max_error

---

## RESPONSE

# operation success or not
bool success
