## file 'CheckSolution.srv'

# who killed Dr Black
string Who
# Where Dr Black was killed
string Where
# What is the murder weapon
string What

---

# is the solution correct?
bool MysterySolved
